# Generated by Django 3.0 on 2020-07-31 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 31, 19, 729050), verbose_name='date published'),
        ),
    ]
