# Generated by Django 3.0 on 2020-08-01 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 40, 11, 560918), verbose_name='date published'),
        ),
    ]
