# Generated by Django 3.0 on 2020-08-04 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200801_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 8, 4, 11, 48, 5, 770584), verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
